# Django REST Framework Router
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TripViewSet

# Create a router and register the TripViewSet
router = DefaultRouter()
router.register(r'trips', TripViewSet, basename='trip')

# The API URLs are now automatically generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
